### PR TITLE
card component for maintenance staff created

### PR DESCRIPTION
**Pull request by josesustaita**
maintenance card component that displays apporiate data regarding WOs, once clicked the card will open up a modal that is a form to edit the WO data

### CODE REVIEW

**Comment by josesustaita** [comment]
[As maintenance, I would like a card component that shows information regarding my work orders](https://trello.com/c/x0ixD38h/15-as-maintenance-i-would-like-a-card-component-that-shows-information-regarding-my-work-orders)

**Review by idongCodes — DISMISSED** [review]
You seem to be very competent in implementing the form handling. Your code is easy to follow. However, I've never seen the way you the method you are using for managing uploads ? what does `new fileReader()` do exactly ? Also curious about the `toISOString()` method .

**Comment by josesustaita** [comment]
> You seem to be very competent in implementing the form handling. Your code is easy to follow. However, I've never seen the way you the method you are using for managing uploads ? what does `new fileReader()` do exactly ? Also curious about the `toISOString()` method .

The fileReader method does exactly as the name implies. Once a file is selected from your computer, this method allows the browser to read what the file is from your computer.  In the file upload function, the function starts out by reading whatever file is selected. Then we are grabbing the data of the file, in this case, an image and finally turning it into base64 with the readAsDataURL method and setting it to the state. As of right now, this is only a temporary solution to implement our file uploads, we have talked about finding a third-party service in which we would upload the files to them and then in return just get back a URL. In regards to the toISOString method, this is just a method that formats dates to yyyy-mm-dd.

**Review by hoangvu71 — COMMENTED** [review]
Nice job Jose. The only thing that I can see that we may discuss is the modal. In my opinion, we can just make it so that by clicking on the card, the card will expand. Then there will be an edit button, by clicking, the modal form will pop up so that we can edit. Do you think that is a good idea?

**Review by hoangvu71 — DISMISSED** [review]

**Review by Cireimu — APPROVED** [review]

**Review by idongCodes — APPROVED** [review]

**Pull request merged**
