### PR TITLE
Barebone work order form

### PR DESCRIPTION
**Pull request by josesustaita**
Still needs state management implemented

### CODE REVIEW

**Comment by josesustaita** [comment]
Added form state for work orders using useState react hook. When you press save on the form it creates an array with the data console logged. Just a placeholder until we can connect it to a backend endpoint

Still need to figure out what we are going to do with the attachment section and how the Back-end will like to receive that data

**Comment by josesustaita** [comment]
[As a Property manager/IT, I want to have a form to fill in work order info so I have a clear idea of the work order that needs to be done](https://trello.com/c/gWxJxEtM/2-as-a-property-manager-it-i-want-to-have-a-form-to-fill-in-work-order-info-so-i-have-a-clear-idea-of-the-work-order-that-needs-to)

**Review by MTaylor-tech — COMMENTED** [review]
Looks good. As far as attachments, we have 3 options: 1) upload the files directly into the database. I don't recommend it. It'll potentially eat up space quickly. 2) upload the files to a third part service on the front end. That service will send back a URL, which we'll store in the DB. I've done this before and it works well. 3) front end sends the backend the file, then we upload the files to a third party service on the backend server. then we save the URL in the DB. I know this works, but I haven't done it before. It shouldn't be a major problem to implement.

**Review by Cireimu — APPROVED** [review]
Looks good, just need you to add back a .env.sample file with the base values since it's missing and causing CI/CD to fail. 

You can do this by creating a new file called `.env.sample`  and adding the following values into: `  
REACT_APP_CLIENT_ID=example
REACT_APP_OKTA_ISSUER_URI="https://example-882474.okta.com"
REACT_APP_API_URI=http://localhost:8005`

**Review by MTaylor-tech — APPROVED** [review]
I thought my previous review had approved these changes. I guess not.

**Pull request merged**
